### PR TITLE
Fix miscellaneous issues with WebSocket closing

### PR DESCRIPTION
**Pull request by tanner0101**
Fixes miscellaneous issues with regards to closing a WebSocket connection (#77)

### CODE REVIEW

**Comment by code28** [comment]
I was investigating for hours to find the problem with the websockets, just to find this PR, which already solved it for me. :) 
What's the progress on this? Do you need help with something or is something blocking you from merging this (except the failing CI)?

**Review by MrLotU — APPROVED** [review]
LGTM

**Comment by tanner0101** [comment]
These changes are now available in [2.1.2](https://github.com/vapor/websocket-kit/releases/tag/2.1.2)

**Comment by lmcd** [comment]
Closing seems completely broken for me... perhaps since this release.

**Pull request merged**
