### PR TITLE
Fix force try in connect method

### PR DESCRIPTION
**Pull request by jameshartt**
Fix force try in `wss://` connect method (#71).

### CODE REVIEW

**Comment by tanner0101** [comment]
Original comment:

---

In very rare circumstances, we're finding these `try!` to be problematic. Just creating a PR to see if we can remove them. Potentially add some logging/other-error-returning. Sometimes OpenSSL can fail to create what it needs and the force try just makes it crash rather than fail gracefully.

**Comment by tanner0101** [comment]
These changes are now available in [2.1.1](https://github.com/vapor/websocket-kit/releases/tag/2.1.1)

**Comment by tanner0101** [comment]
Thanks!

**Comment by jameshartt** [comment]
Thanks @tanner0101! :smile:

**Pull request merged**
